### PR TITLE
Add classes and logic for GAS/GAP and according unit types

### PR DESCRIPTION
**Pull request by jimmykane**
This should add all the autogenereted stats/streams etc for GAP/GAS

### CODE REVIEW

**Comment by jimmykane** [comment]
@thomaschampagne PR is ready. Maybe a cross check and we can merge and more on using GAS/GAP

**Comment by thomaschampagne** [comment]
@jimmykane Sorry i have been quite busy last days. I will check/test this evening or tomorrow ;)

**Comment by jimmykane** [comment]
I ll go on merging this , I have already deployed this to prod and looks fine :-) 

Will be covering with tests etc once we get the new stuff in :-D

**Comment by thomaschampagne** [comment]
Ok no problem. It will perform the review by the way. You can cherry pick things you want ;)

**Pull request merged**
