### PR TITLE
Globals improvements

### PR DESCRIPTION
**Pull request by thomaschampagne**
I'm on below since May 2021 :D. 

I improved many things weeks after weeks with a deep analysis of:
- How activities could be handled by others platforms like garmin or strava (and for every file types).
- Every change made in this lib and impacts on activities' data consistency through integration tests + debug tools (I created inside my Elevate desktop app).

## Pull-request content:

- Support real moving time, timer time & pause time for each file types:
    - Handle times per sports: rides, runs, swim and generics ones
    - Support specific moving time for swim activities in pools (based on active laps).
- Testing
    - Rework of integration tests by sports and file types
    - Added a SpecUtils class for integration tests to perform assertions along "near values" or "near military time"
    - Added new integration tests to improve consistency and robustness
    - Added new assertions on existing ones to improve consistency and robustness
- Fixes:
    - Fixed power stream compliance when in some cases power sample field is missing from records (=set power to 0)
    - Fixed parse crash when some fit file could not have any sessions declared at all. Now returning a `EmptyEventLibError` exception.
    - Fixed various start/end date issues on some fit files provided by the "Elevate" community.
    - Fixed GPX parse crash which could occur when some GPX samples may have a missing time value.
    - Fixed case where "Indoor" activities were not flagged as is when GPS data was missing.
    - Fixed pace not exactly matching grade adjusted pace when grade is 0%
    - Fixed many other parse crashes based of thousands of files from "Elevate" community
 > When a bug is fixed I usually add an integration test or a new assertion into existing test to avoid regressions.
- Events:
    - Added `FileType` enum property to event object
- Activities:
    - Added `getAllRiderPositionChangeEvents()` method: provides rider position change events (`SEATED`, `STANDING` and Transitions).
    - Added `hasLaps()`: do what it says :)
    - Added `replaceStreamData(streamType: string, data: (number | null)[])`: do what it says :)
- New stats:
    - Swim:
        - SWOLF 25m pool
        - SWOLF 50m pool
        - Active Lengths count
    - Cycling:
        - Seated Time
        - Standing Time
        - Power Pedal Smoothness L/R
        - Power Torque Effectiveness L/R
        - Power Intensity Factor
        - Power Normalized
        - Power Training Stress Score (TSS)
    - Running:
        - Stance Time Balance L/R
        - Avg Stride Length
    - Any:
        - Is ActiveLap on each laps
        - Total Cycles (crankset revs, strokes count, strides count)
        - Added anaerobic training effect (along side existing aerobic training effect)
        - Power Work (Kilo Joule)
- Streams:
    - Added Altitude Smoothed
    - Improved & Added Grade Smooth stream. It's now computed from Altitude Smoothed stream and processed with proper Kalman params (old params with R: 1, Q: 1 just does... nothing to the signal :)). This grade stream has been deep tested and validated on many activities.
    - Added RightStanceTimeBalance stream alongside StanceTimeBalanceLeft
    - Generate streams based on activity lengths when available. Indeed, activities don't provide full samples data from records objects. This is the case in pool swimming activities for instance (Strava streams handle this as is for this kind of activities).
    - Added `ActivityUtilities::shapeStream` method which provides squashed stream data through a callback for data manipulation & rebuild the stream based on duration including the missing values (null, Infinity, ...) provided by source stream
    - Added `medianFilter` & `meanWindowSmoothing` utils to shape streams
- Laps:
    - Added index to laps
    - Added start/end stream indexes: This allow to identify a stream section based on these lap start/end indexes.
    - Added every possible stats we can add on provided laps from the file type source.
- Creator:
  - Rework creator name formatting through unit testing
  - Updated Garmin products list with new device released since today
  - Added Some Wahoo, Lezyne, Magellan, ... devices
  - Reduce size of device names definitions
  - Added productId, manufacturer and a "isRecognized" (by the lib) attributes. This enables me to detect unsupported devices name I will populate back to the library but with proper device names.
- Completed work behind export/import as JSON (Events => Activities => streams)
- Rework improved how activity start/end date are being calculated
- Added a flexible activity parsing options mechanism. You pass options when calling a sports-lib importer. Currently you can enable/disable these stream calculations => Atl Smooth, Grade & Grade Smooth.
- Rework lib exceptions structure with errors codes (because when using lib in workers (Yes it's "compute" lib :)) we loose errors instances prototypes)

### CODE REVIEW

**Comment by jimmykane** [comment]
Looks good so far !

**Comment by thomaschampagne** [comment]
Hey @jimmykane ! Do you have an idea on how we can improve the process performance of activities like this one:
[3161ddf751-6005237297.zip](https://github.com/sports-alliance/sports-lib/files/7455012/3161ddf751-6005237297.zip) (https://www.strava.com/activities/6197356353)?

The problem is that the **end date** is **~27 days** after the **start date**. It generate 2.5 millions on samples (mostly `null`) and `computeGradeStreamBasedOnDistance` method takes many minutes to complete. I didn't fully measure because way too long....

I have been able to perform grade calculation on distance & altitude squashed streams, and I rebuild a 2.5 millions samples grade stream.... It takes 4 seconds to process the activity. But I don't have same final grade stream than you (It's not commited)

What's your opinion or fix ideas for this? 

Thanks to U !

**Comment by thomaschampagne** [comment]
Now using my own grade calculator based on distance only. Results are consistents. The parsing performance just bumped :D !

**Comment by thomaschampagne** [comment]
Hey @jimmykane ! My PR is now live for review 😃 !! Few questions before merging:

- Does this PR bump the lib to version 6.0.0 for you?
- Is yarn v1 still a thing and usefull for this lib since npm v7?

Happy review !

Thomas

**Comment by thomaschampagne** [comment]
Wait a bit finally :)

**Comment by jimmykane** [comment]
😅

Will start reviewing tomorrow

**Comment by thomaschampagne** [comment]
@jimmykane I finally haven't been able rework the legacy grade calculation method located at: 

- [computeGradeStreamBasedOnDistance](https://github.com/sports-alliance/sports-lib/blob/feature/improve-stats-accuracy/src/events/utilities/grade-calculator/grade-calculator.ts#L86)
-  And [computeGradeStreamBasedOnAltitude](https://github.com/sports-alliance/sports-lib/blob/feature/improve-stats-accuracy/src/events/utilities/grade-calculator/grade-calculator.ts#L145)

I tried but don't have the sufficient step back on the lib to fix issues I seen. Indeed I think this grade calculation should be reworked because of strong performance isssues.

I created an [integration test here](https://github.com/sports-alliance/sports-lib/blob/feature/improve-stats-accuracy/src/specs/activities-parsing.integration.spec.ts#L2259) which highlight the issue (remove the "skip" call to see the drama 😄). 

As i wrote in the test comment, this test/activity takes too much time to complete: the activity elapsed time is very high and the current grade computation code tries to fill up missing data for years.... 

> ➡️ The grade calculation should be performed on a **squashed** and **lenght aligned** distance/altitude streams.

To fix the issue, I inspired myself from the [shapeStream method](https://github.com/sports-alliance/sports-lib/blob/feature/improve-stats-accuracy/src/events/utilities/activity.utilities.ts#L1144) I previously coded. It fix the performance issue and integration test above. Howerver I haven't been able to manage this when squashed distance/altitude streams don't have same size.

> ➡️ Could you tell me If you can take a look/re-rework this method on this branch❓ Else I will dive again into it to fix the issue.

Also I think that calculating grade on distance only is sufficient. 

Because of above issue, I had to handle by the grade computation on my side for my app (using squashed streams). You can inspire/retrieve code from my [computeShapeGrade method](https://github.com/thomaschampagne/elevate/blob/7.0.0/appcore/modules/shared/sync/compute/stream-processor.ts#L142) . Using this code and after deep activities analysis and integration testing, I got very consistent results on grades and consequently on grade adujsted paces, estimated power, etc... I can show you if you need.  The strava grade smooth stream is not as reliable as we might think: there's often impossibles grades within. I seen that in my weeks of analysis....

Thanks for your help in this in advance!

Ask me anything,

Thomas

**Comment by thomaschampagne** [comment]
@jimmykane about the issue I raised on [my above comment](https://github.com/sports-alliance/sports-lib/pull/91#issuecomment-968219389), I'm currently  on something... I update you if problem is finally solved or not. Don't work on it at the moment ;)

**Comment by thomaschampagne** [comment]
@jimmykane I have been to solve [the issue I raised](https://github.com/sports-alliance/sports-lib/pull/91#issuecomment-968219389). Just need to perform more testing, validation & refactoring/clean-up and I push.

**Comment by thomaschampagne** [comment]
@jimmykane It should be OK for a review now ;)

**Comment by jimmykane** [comment]
LGTM. 

If you are using this branch go ahead and merge.

**Pull request merged**
